version: "3"

services:
  app:
    build:
      context: .
      args:
        - ENV=test
    container_name: app_test
    volumes:
      - ./app:/app/app:ro
      - ./tests:/app/tests:ro
    environment:
      - DB_HOST=test_database
      - DATABASE=_test
      - DB_USER=gfw
      - DB_PASSWORD=postgres  # pragma: allowlist secret
      - DB_PORT=5432
      - DB_HOST_RO=test_database
      - DATABASE_RO=_test
      - DB_USER_RO=gfw_readonly
      - DB_PASSWORD_RO=readonly  # pragma: allowlist secret
      - DB_PORT_RO=5432
      - LOG_LEVEL=debug
    entrypoint: wait_for_postgres.sh pytest
    depends_on:
      - test_database

  test_database:
    container_name: gfw-data-api-test-database
    image: postgis/postgis:11-3.0-alpine
    ports:
      - 54320:5432
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=_test
      - POSTGRES_USER=gfw
      - POSTGRES_PASSWORD=postgres  # pragma: allowlist secret
    volumes:
      - test_database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gfw"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  test_database_data:
