version: "3"

services:
  app:
    container_name: gfw-data-api
    image: gfw-data-api
    volumes:
      - $HOME/.aws:/root/.aws:ro
    environment:
      - DB_HOST=database
      - DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - AWS_DEFAULT_PROFILE=gfw-dev
      - ENV=docker
    depends_on:
      - database

  database:
    image: "gfw/postgres"
    container_name: database
    restart: always
    ports:
      - 54320:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
