name: Run tests and apply terraform changes for current branch

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Test with pytest
      run: |
        ./scripts/test -b ${{github.ref}} -k ${{ secrets.aws_key_dev }} -s ${{ secrets.aws_secret_dev }}


    - name: Build Container
      if: success()
      run: ./scripts/cibuild ${{github.ref}}

    - name: Deploy production
      if: success() && contains(github.ref, 'master')
      env:
        ENV: production
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_production }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_production }}
        AWS_DEFAULT_REGION: ${{ secrets.aws_region_production }}
      run: |
        ./scripts/infra plan
        ./scripts/infra apply

    - name: Deploy staging
      if: success() && contains(github.ref, 'develop')
      env:
        ENV: staging
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_staging }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_staging }}
        AWS_DEFAULT_REGION: ${{ secrets.aws_region_staging }}
      run: |
        ./scripts/infra plan
        ./scripts/infra apply

    - name: Deploy dev
      if: success() && (! contains(github.ref, 'develop')) && (! contains(github.ref, 'master'))
      env:
        ENV: dev
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_dev }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_dev }}
        AWS_DEFAULT_REGION: ${{ secrets.aws_region_dev }}
      run: |
        ./scripts/infra plan
        ./scripts/infra apply